# Generated by Django 5.1.7 on 2025-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('academico', 'Académico'), ('deportivo', 'Deportivo'), ('cultural', 'Cultural')], max_length=20)),
            ],
        ),
    ]
