# Generated by Django 5.1.5 on 2025-04-08 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_club_horario_reunion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='clubes', to=settings.AUTH_USER_MODEL),
        ),
    ]
