# Generated by Django 5.1.7 on 2025-03-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votacion',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='foros.foro'),
        ),
    ]
