# Generated by Django 4.2.11 on 2025-03-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0003_foro_fecha_creacion_alter_votacion_foro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='votacion',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.foro'),
        ),
    ]
