# Generated by Django 4.2.11 on 2025-03-28 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0004_remove_foro_fecha_creacion_alter_votacion_foro'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
